/**
Procedura usuwujaca tabele i sekwencje, jeśli istnieją
*/


DECLARE
    v_count  INT;
    v_name VARCHAR2(30);
    TYPE namesarray IS VARRAY(13) OF VARCHAR2(30);
    names    namesarray;
    TYPE sequencesarray IS VARRAY(2) OF VARCHAR2(30);
    sequences    sequencesarray;
BEGIN
    names := namesarray('archived_groups', 'archived_memberships', 'categories', 'currencies', 'expenses', 'groups',
                        'memberships', 'methods_of_payment', 'preferences', 'refresh_tokens',
                        'roles', 'temporary_memberships', 'users');

    sequences := sequencesarray('base_group_seq', 'base_membership_seq');

    FOR i IN 1..names.count LOOP
        v_name := names(i);

        SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = upper(v_name);
        IF v_count = 1 THEN
            DBMS_OUTPUT.PUT_LINE('Dropping table: ' || v_name);
            EXECUTE IMMEDIATE 'DROP TABLE '|| v_name || ' CASCADE CONSTRAINTS';
        END IF;
    END LOOP;

    FOR i IN 1..sequences.count LOOP
        v_name := sequences(i);

        SELECT COUNT(*) INTO v_count FROM user_sequences WHERE sequence_name = upper(v_name);
        IF v_count = 1 THEN
            DBMS_OUTPUT.PUT_LINE('Dropping sequence: ' || v_name);
            EXECUTE IMMEDIATE 'DROP SEQUENCE '|| v_name;
        END IF;
    END LOOP;
END;

/


create sequence base_group_seq start with 1 increment by 1;

create sequence base_membership_seq start with 1 increment by 1;

create table archived_groups (
    id number(6,0) not null,
    name varchar2(255 char) not null,
    primary key (id)
);

create table archived_memberships (
    group_id number(6,0) not null,
    id number(6,0) not null,
    role_id number(6,0) not null,
    user_id number(6,0) not null,
    primary key (id)
);

create table categories (
    id number(6,0) generated by default as identity,
    name varchar2(255 char) not null,
    primary key (id),
    unique (name)
);

create table currencies (
    exchange_rate float(53) not null,
    id number(6,0) generated by default as identity,
    symbol varchar2(255 char) not null,
    primary key (id),
    unique (symbol)
);

create table expenses (
    expense_date date not null,
    price float(53) not null,
    category_id number(6,0) not null,
    currency_id number(6,0) not null,
    id number(6,0) generated by default as identity,
    membership_id number(6,0) not null,
    method_id number(6,0) not null,
    title varchar2(255 char) not null,
    primary key (id)
);

create table groups (
    id number(6,0) not null,
    name varchar2(255 char) not null,
    primary key (id)
);

create table memberships (
    group_id number(6,0) not null,
    id number(6,0) not null,
    role_id number(6,0) not null,
    user_id number(6,0) not null,
    primary key (id)
);

create table methods_of_payment (
    id number(6,0) generated by default as identity,
    name varchar2(255 char) not null,
    primary key (id),
    unique (name)
);

create table preferences (
    currency_id number(6,0) not null,
    id number(6,0) generated by default as identity,
    method_id number(6,0) not null,
    language varchar2(255 char) not null,
    primary key (id)
);

create table refresh_tokens (
    expiry_date timestamp(6) with time zone not null,
    id number(6,0) generated by default as identity,
    user_id number(6,0) not null unique,
    token varchar2(255 char) not null unique,
    primary key (id)
);

create table roles (
    id number(6,0) generated by default as identity,
    name varchar2(255 char) not null,
    primary key (id),
    unique (name)
);

create table temporary_memberships (
    group_id number(6,0) not null,
    id number(6,0) generated by default as identity,
    role_id number(6,0) not null,
    sender_id number(6,0) not null,
    user_id number(6,0) not null,
    primary key (id)
);

create table users (
    creation_date date not null,
    id number(6,0) generated by default as identity,
    preferences_id number(6,0) not null unique,
    email varchar2(255 char) not null unique,
    name varchar2(255 char) not null,
    password varchar2(255 char) not null,
    surname varchar2(255 char) not null,
    primary key (id)
);

alter table archived_memberships
    add constraint archived_memberships_group_id_fk
        foreign key (group_id)
        references archived_groups
    add constraint archived_memberships_role_id_fk
        foreign key (role_id)
        references roles
    add constraint archived_memberships_user_id_fk
        foreign key (user_id)
        references users;

alter table expenses
    add constraint expenses_category_id_fk
        foreign key (category_id)
        references categories
    add constraint expenses_currency_id_fk
        foreign key (currency_id)
        references currencies
    add constraint expenses_membership_id_fk
        foreign key (membership_id)
        references memberships
    add constraint expenses_method_id_fk
        foreign key (method_id)
        references methods_of_payment;

alter table memberships
    add constraint memberships_group_id_fk
        foreign key (group_id)
        references groups
    add constraint memberships_role_id_fk
        foreign key (role_id)
        references roles
    add constraint memberships_user_id_fk
        foreign key (user_id)
        references users;

alter table preferences
    add constraint preferences_currency_id_fk
        foreign key (currency_id)
        references currencies
    add constraint preferences_method_id_fk
        foreign key (method_id)
        references methods_of_payment;

alter table refresh_tokens
    add constraint refresh_tokens_user_id_fk
        foreign key (user_id)
        references users;

alter table temporary_memberships
    add constraint temporary_memberships_group_id_fk
        foreign key (group_id)
        references groups
    add constraint temporary_memberships_role_id_fk
        foreign key (role_id)
        references roles
    add constraint temporary_memberships_user_id_fk
        foreign key (user_id)
        references users
    add constraint temporary_memberships_sender_id_fk
        foreign key (sender_id)
        references users;

alter table users
    add constraint users_preferences_id_fk
        foreign key (preferences_id)
        references preferences;

COMMIT;
