/**
  Returns id of user who spent the most in given group, returns -1 if no expenses in group
 */
CREATE OR REPLACE FUNCTION MOST_SPENDING_USER_IN_GROUP(
    G_ID NUMBER
) RETURN NUMBER AS
    V_USER_ID  NUMBER := -1;
    V_SPENDING NUMBER;
BEGIN
    SELECT M.USER_ID,
           SUM(GET_EXPENSE_PRICE_IN_ANOTHER_CURR(
                   E.ID,
                   1
               )) AS TOTALSPENDING
    INTO
        V_USER_ID,
        V_SPENDING
    FROM MEMBERSHIPS M
             JOIN EXPENSES E
                  ON M.ID = E.MEMBERSHIP_ID
    WHERE M.GROUP_ID = G_ID
    GROUP BY M.USER_ID
    UNION
    SELECT -1, -1
    FROM DUAL
    ORDER BY TOTALSPENDING DESC
        FETCH FIRST 1 ROWS ONLY;

    RETURN V_USER_ID;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(MOST_SPENDING_USER_IN_GROUP(5));
END;
/

/**
  Returns date when given group spent the most, if no expenses in given group returns null
 */
CREATE OR REPLACE FUNCTION GET_DATE_WITH_MOST_SPENDING(G_ID NUMBER) RETURN DATE AS
    V_DATE DATE;
    V_TOTAL_SPENDING NUMBER;
BEGIN
    SELECT E.EXPENSE_DATE, SUM(GET_EXPENSE_PRICE_IN_ANOTHER_CURR(E.ID, 1)) AS TOTAL_SPENDING
    INTO V_DATE, V_TOTAL_SPENDING
    FROM EXPENSES E
             JOIN MEMBERSHIPS M ON E.MEMBERSHIP_ID = M.ID
             JOIN GROUPS G ON M.GROUP_ID = G.ID
    WHERE G.ID = G_ID
    GROUP BY EXPENSE_DATE
    UNION
    SELECT NULL, -1
    FROM DUAL
    ORDER BY TOTAL_SPENDING DESC FETCH FIRST 1 ROWS ONLY;

    RETURN V_DATE;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(GET_DATE_WITH_MOST_SPENDING(4));
END;
/

/**
  Returns expense price in another currency
 */
CREATE OR REPLACE FUNCTION GET_EXPENSE_PRICE_IN_ANOTHER_CURR(EXPENSE_ID NUMBER, CURR_ID NUMBER)
    RETURN NUMBER
AS
    V_PRICE NUMBER;
    V_SRC_ER NUMBER;
    V_DEST_ER NUMBER;
BEGIN
    SELECT E.PRICE, C.EXCHANGE_RATE INTO V_PRICE, V_SRC_ER FROM EXPENSES E
    JOIN CURRENCIES C ON (E.CURRENCY_ID = C.ID)
    WHERE E.ID = EXPENSE_ID;

    SELECT EXCHANGE_RATE INTO V_DEST_ER FROM CURRENCIES WHERE ID = CURR_ID;

    V_PRICE := ( V_PRICE * V_SRC_ER) / V_DEST_ER;
    RETURN V_PRICE;
END;
/
