/*
Trigger to archive deleted groups
 */
CREATE OR REPLACE TRIGGER ARCHIVE_GROUP
BEFORE DELETE ON GROUPS
FOR EACH ROW
BEGIN
INSERT INTO ARCHIVED_GROUPS (ID, NAME)
VALUES (BASE_GROUP_SEQ.NEXTVAL, :OLD.NAME);
END;
/


/*
Trigger to archive deleted memberships
 */
CREATE OR REPLACE TRIGGER ARCHIVE_MEMBERSHIP
BEFORE DELETE ON MEMBERSHIPS
FOR EACH ROW
BEGIN
INSERT INTO ARCHIVED_MEMBERSHIPS (ID, GROUP_ID, USER_ID, ROLE_ID)
VALUES (BASE_MEMBERSHIP_SEQ.NEXTVAL, :OLD.GROUP_ID, :OLD.USER_ID, :OLD.ROLE_ID);
END;
/


/*
Trigger to fill creation_date for newly created user if empty
 */
CREATE OR REPLACE TRIGGER FILL_CREATION_DATE
BEFORE INSERT ON USERS
FOR EACH ROW
WHEN (NEW.CREATION_DATE IS NULL)
BEGIN
    :NEW.CREATION_DATE := SYSDATE;
END;
/

/*
Trigger to set new admins for group
 */
CREATE OR REPLACE TRIGGER SET_NEW_ADMIN
BEFORE DELETE ON MEMBERSHIPS
FOR EACH ROW
WHEN (OLD.ROLE_ID = 3)
BEGIN
    IF NOT EXISTS (SELECT * FROM MEMBERSHIPS WHERE GROUP_ID = :OLD.GROUP_ID AND ROLE_ID = 3) THEN
        IF EXISTS (SELECT * FROM MEMBERSHIPS WHERE GROUP_ID = :OLD.GROUP_ID AND ROLE_ID = 2) THEN
UPDATE MEMBERSHIPS
SET ROLE_ID = 3
WHERE GROUP_ID = :OLD.GROUP_ID AND ROLE_ID = 2;
ELSIF EXISTS (SELECT * FROM MEMBERSHIPS WHERE GROUP_ID = :OLD.GROUP_ID AND ROLE_ID = 1) THEN
UPDATE MEMBERSHIPS
SET ROLE_ID = 3
WHERE GROUP_ID = :OLD.GROUP_ID AND ROLE_ID = 1;
ELSIF EXISTS (SELECT * FROM MEMBERSHIPS WHERE GROUP_ID = :OLD.GROUP_ID AND ROLE_ID = 4) THEN
UPDATE MEMBERSHIPS
SET ROLE_ID = 3
WHERE GROUP_ID = :OLD.GROUP_ID AND ROLE_ID = 4;
END IF;
END IF;
END;