/*
Trigger to archive deleted groups
 */
CREATE OR REPLACE TRIGGER ARCHIVE_GROUP
BEFORE DELETE ON GROUPS
FOR EACH ROW
BEGIN
INSERT INTO ARCHIVED_GROUPS (ID, NAME)
VALUES (BASE_GROUP_SEQ.NEXTVAL, :OLD.NAME);
END;
/


/*
Trigger to archive deleted memberships
 */
CREATE OR REPLACE TRIGGER ARCHIVE_MEMBERSHIP
BEFORE DELETE ON MEMBERSHIPS
FOR EACH ROW
BEGIN
INSERT INTO ARCHIVED_MEMBERSHIPS (ID, GROUP_ID, USER_ID, ROLE_ID)
VALUES (BASE_MEMBERSHIP_SEQ.NEXTVAL, :OLD.GROUP_ID, :OLD.USER_ID, :OLD.ROLE_ID);
END;
/


/*
Trigger to fill creation_date for newly created user if empty
 */
CREATE OR REPLACE TRIGGER FILL_CREATION_DATE
BEFORE INSERT ON USERS
FOR EACH ROW
WHEN (NEW.CREATION_DATE IS NULL)
BEGIN
    :NEW.CREATION_DATE := SYSDATE;
END;
/